In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
import numpy as np 
from sklearn.naive_bayes import GaussianNB

In [2]:
df = pd.read_csv("migration_nz.csv")
df.head()

Measure     Country             Citizenship  Year    Value
0  Arrivals     Oceania     New Zealand Citizen  1979  11817.0
1  Arrivals     Oceania      Australian Citizen  1979   4436.0
2  Arrivals     Oceania  Total All Citizenships  1979  19965.0
3  Arrivals  Antarctica     New Zealand Citizen  1979     10.0
4  Arrivals  Antarctica      Australian Citizen  1979      0.0

In [3]:
df['Measure'].unique()

array(['Arrivals', 'Departures', 'Net'], dtype=object)

In [4]:
df['Measureid'] = pd.factorize(df.Measure)[0]
df['Measureid'].unique()

array([0, 1, 2], dtype=int64)

In [5]:
df['CountryID'] = pd.factorize(df.Country)[0]
df['CountryID'].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [6]:
df['Citizenship'].unique()

array(['New Zealand Citizen', 'Australian Citizen',
       'Total All Citizenships'], dtype=object)

In [7]:
df['Year'].unique()

array([1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989,
       1990, 1991, 1994, 1992, 1993, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2016, 2015], dtype=int64)

In [8]:
df.isnull().sum()

Measure         0
Country         0
Citizenship     0
Year            0
Value          72
Measureid       0
CountryID       0
dtype: int64

In [9]:
df["Value"].fillna(df["Value"].median(),inplace=True)

In [10]:
df.isnull().sum()

Measure        0
Country        0
Citizenship    0
Year           0
Value          0
Measureid      0
CountryID      0
dtype: int64